import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/app/styles/reset.css'
import Header from "./header/page";
import Footer from "./footer/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
